services:
  pbx:
    # Use pre-built image from Docker Hub
    # fusionpbx 5.2 is old theme(5.4 is new theme)
    image: michaelfangtw/fusionpbx-docker:5.2

    # Or build locally (uncomment to use)
    # build:
    #   context: .

    # Host networking for RTP port range
    network_mode: "host"
    container_name: fusionpbx
    restart: always
    privileged: true

    # Persist configuration
    volumes:
      - ./config/fusionpbx:/etc/fusionpbx

    entrypoint: ["/usr/sbin/init"]
